app/main/forms.py
from wtforms import StringField, SubmitField, SelectField, DateField
from wtforms.validators import Required, Length, Email, Optional, URL, Length
from flask.ext.wtf import Form
from wtforms import ValidationError
from ..models import User
from flask.ext.login import current_user
class PersonalForm(Form):
	username = StringField('Username', validators=[Required(), Length(5, 64)])
	firstname = StringField('First Name', validators=[Optional()])
	midname = StringField('Mid Name', validators=[Optional()])
	lastname = StringField('Last Name', validators=[Optional()])
	phone = StringField('Phone', validators=[Optional()])
	birthday = DateField("Birthday format(dd/mm/yyyy)", format="%d/%m/%Y", validators=[Optional()])
	gender = SelectField('Gender', default="None", choices=[
		("None", ""),
		("Male", "Male"),
		("Female", "Female")])
	location = StringField("Location", validators=[Optional()])
	website = StringField("Website", validators=[Optional(), URL()])
	skype = StringField("Skype Username", validators=[Optional()])
	instagram = StringField("Instagram username", validators=[Optional()])
	vk = StringField("http://vk.com/", validators=[Optional()])
	googleplus = StringField("Google ID", validators=[Optional()])
	github = StringField("Github Username", validators=[Optional()])
	twitch = StringField("Twitch Username", validators=[Optional()])
	tumblr = StringField("Tumblr Username", validators=[Optional()])
	reddit = StringField("Reddit Username", validators=[Optional()])
	linkedin = StringField("Linkedin ID", validators=[Optional()])
	soundcloud = StringField("Soundcloud", validators=[Optional()])
	steam = StringField("Steam", validators=[Optional()])
	pinterest = StringField("Pinterest", validators=[Optional()])
	alibaba = StringField("Alibaba Company name", validators=[Optional()])
	submit = SubmitField("Save")

	def validate_username(self, field):
		find = User.query.filter_by(username=field.data).first()
		if find and not (find == current_user):
			raise ValidationError('Username is already in use')

app/main/__init__.py
from flask import Blueprint
main = Blueprint('main', __name__)
from . import views

app/main/views.py
from . import main
from .forms import PersonalForm
from ..models import User, Follow
from flask import request, render_template, flash, redirect, current_app, url_for, g
from flask.ext.login import current_user, login_required
from werkzeug import secure_filename
import os


@main.route('/', methods=['POST', 'GET'])
def index():

	if current_user.is_authenticated():
		recent_connect_user = User.query.join(Follow, Follow.followed_id == User.id).filter(Follow.follower_id == current_user.id)
		form = PersonalForm(obj=current_user)
		if form.validate_on_submit():
			form.populate_obj(current_user)
			current_user.save()
			flash('Updated')
		return render_template('main/user_index.html', form=form, recent_connect_user=recent_connect_user)
	else:
		return render_template('main/index.html')
# Do not have premission on my own Windows, allow it when deploy
# def allowed_avatar_file(filename):
# 	return '.' in filename and filename.rsplit('.', 1)[1] in current_app.config['ALLOWED_EXTENSIONS']

# @main.route('/upload_avatar', methods=['POST', 'GET'])
# def upload_avatar():
# 	if current_user.is_authenticated():
# 		if request.method == 'POST':
# 			file = request.files['file']
# 			if file and allowed_avatar_file(file.filename.lower()):
# 				base = secure_filename(file.filename).rsplit('.',1)[0]

# 				file.save(current_app.config['UPLOAD_FOLDER'])
# 				flash('You have uploaded your avatar')
# 				return redirect(url_for('main.index'))
# 			else:
# 				return redirect(url_for('auth.register'))
@main.route('/user/<username>')
@login_required
def profile(username):
	user = User.query.filter_by(username=username).first_or_404()
	return render_template("main/user_profile.html", user=user)

@main.route('/user/<username>/connect')
@login_required
def connect_user(username):
	user = User.query.filter_by(username=username).first_or_404()
	current_user.follow(user)
	return redirect(url_for('main.profile', username=username))

@main.route('/user/<username>/disconnect')
@login_required
def disconnect_user(username):
	user = User.query.filter_by(username=username).first_or_404()
	current_user.unfollow(user)
	return redirect(url_for('main.profile', username=username))

@main.route('/search/<query>')
def search(query):
	results = User.query.whoosh_search(query).all()
	return render_template("main/search_result.html", results=results, query=query)

app/templates/main/index.html
{% extends "base.html" %}
{% block title %} Hello {% endblock %}
{% block page_content %}
  <div style="background: #3276b1; color: #FFF" class="jumbotron">
    <div class="container">
      <h1>New ID</h1>
      <p>New way to connect</p>
    </div>
  </div>
{% endblock %}

app/templates/main/search_result.html
{% extends "base.html" %}

{% block content %}
  <h1>Search users for "{{ query }}":</h1>
  {% for user in results %}
    <a href="{{url_for('main.profile', username=user.username)}}">user profile</a>
  {% endfor %}
{% endblock %}

app/templates/main/user_index.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf%}
{% block title %}New ID - {{ current_user.username }}{% endblock %}
{% block styles %}
  {{super()}}
  <link href="//cdnjs.cloudflare.com/ajax/libs/x-editable/1.5.0/bootstrap3-editable/css/bootstrap-editable.css" rel="stylesheet"/>
{% endblock %}


{% block page_content %}
<div class="page-header">
    <h1>Hello, {% if current_user.is_authenticated() %}{{ current_user.username }}{% else %}Stranger{% endif %}!</h1>
</div>
<div class="row">
	<div class="col-md-6">
		<img class="center-block" src="{{ qrcode(request.url_root + url_for('main.profile', username=current_user.username)[1:]) }}">

    <!-- twitter   -->
    {% if not current_user.twitter or current_user.twitter == "" %}
    <a href="{{url_for('social.twitter_login')}}">
      <i style="color: #CCCCCC;" class="fa fa-twitter fa-5x"></i>
      </a>
    {% else %}
      <a href="{{url_for('social.twitter_logout')}}" alt="disconnect">
        <i style="color: #000;"class="fa fa-twitter fa-5x"></i>
      </a>
    {% endif %}
    <!-- twitter   end -->
    <!-- spotify   start -->
    {% if not current_user.spotify or current_user.spotify == "" %}
    <a href="{{url_for('social.spotify_login')}}">
      <i style="color: #CCCCCC;" class="fa fa-spotify fa-5x"></i>
    </a>
    {% else %}
      <a href="{{url_for('social.spotify_logout')}}">
        <i style="color: #000;" class="fa fa-spotify fa-5x"></i>
      </a>
    {% endif %}
    <!-- spotify   end -->
    <!-- skype   start -->
    {% if not current_user.skype or current_user.skype == "" %}
    <!-- <a style="border-bottom: none;" href="#" id="skype" data-type="text" data-title="Enter Skype username"> -->
    <a href="">
      <i style="color: #CCCCCC;" class="fa fa-skype fa-5x"></i>
    </a>
    {% else %}
      <a href="">
        <i style="color: #000;" class="fa fa-skype fa-5x"></i>
      </a>
    {% endif %}
    <!-- skype   end -->
    <!-- instagram   start -->
    {% if not current_user.instagram or current_user.instagram == "" %}
    <a href="">
      <i style="color: #CCCCCC;" class="fa fa-instagram fa-5x"></i>
    </a>
    {% else %}
      <a href="">
        <i style="color: #000;" class="fa fa-instagram fa-5x"></i>
      </a>
    {% endif %}
    <!-- instagram   end -->
    <!-- vk start -->
    {% if not current_user.vk or current_user.vk == "" %}
	   <a href="">
       <i style="color: #CCCCCC;" class="fa fa-vk fa-5x"></i>
     </a>
	  {% else %}
     <a href="">
       <i style="color: #000;" class="fa fa-vk fa-5x"></i>
     </a>
    {% endif %}
    <!-- vk end -->
    <!-- googleplus start -->
    {% if not current_user.googleplus or current_user.googleplus == "" %}
	   <a href="">
       <i style="color: #CCCCCC;" class="fa fa-google-plus fa-5x"></i>
     </a>
	  {% else %}
     <a href="">
       <i style="color: #000;" class="fa fa-google-plus fa-5x"></i>
     </a>
    {% endif %}
    <!-- googleplus end -->
    <!-- github start -->
    {% if not current_user.github or current_user.github == "" %}
	   <a href="">
       <i style="color: #CCCCCC;" class="fa fa-github fa-5x"></i>
     </a>
	  {% else %}
     <a href="">
       <i style="color: #000;" class="fa fa-github fa-5x"></i>
     </a>
    {% endif %}
    <!-- github end -->
    <!-- twitch start -->
    {% if not current_user.twitch or current_user.twitch == "" %}
	   <a href="">
       <i style="color: #CCCCCC;" class="fa fa-twitch fa-5x"></i>
     </a>
	  {% else %}
     <a href="">
       <i style="color: #000;" class="fa fa-twitch fa-5x"></i>
     </a>
    {% endif %}
    <!-- twitch end -->
    <!-- reddit start -->
    {% if not current_user.reddit or current_user.reddit == "" %}
	   <a href="">
       <i style="color: #CCCCCC;" class="fa fa-reddit fa-5x"></i>
     </a>
	  {% else %}
     <a href="">
       <i style="color: #000;" class="fa fa-reddit fa-5x"></i>
     </a>
    {% endif %}
    <!-- reddit end -->
    <!-- linkedin start -->
    {% if not current_user.linkedin or current_user.linkedin == "" %}
	   <a href="">
       <i style="color: #CCCCCC;" class="fa fa-linkedin fa-5x"></i>
     </a>
	  {% else %}
     <a href="">
       <i style="color: #000;" class="fa fa-linkedin fa-5x"></i>
     </a>
    {% endif %}
    <!-- linkedin end -->
    <!-- soundcloud start -->
    {% if not current_user.soundcloud or current_user.soundcloud == "" %}
	   <a href="">
       <i style="color: #CCCCCC;" class="fa fa-soundcloud fa-5x"></i>
     </a>
	  {% else %}
     <a href="">
       <i style="color: #000;" class="fa fa-soundcloud fa-5x"></i>
     </a>
    {% endif %}
    <!-- soundcloud end -->
    <!-- steam start -->
    {% if not current_user.steam or current_user.steam == "" %}
	   <a href="">
       <i style="color: #CCCCCC;" class="fa fa-steam fa-5x"></i>
     </a>
	  {% else %}
     <a href="">
       <i style="color: #000;" class="fa fa-steam fa-5x"></i>
     </a>
    {% endif %}
    <!-- steam end -->
    <!-- pinterest start -->
    {% if not current_user.pinterest or current_user.pinterest == "" %}
	   <a href="">
       <i style="color: #CCCCCC;" class="fa fa-pinterest fa-5x"></i>
     </a>
	  {% else %}
     <a href="">
       <i style="color: #000;" class="fa fa-pinterest fa-5x"></i>
     </a>
    {% endif %}
    <!-- pinterest end -->


    <br>


    <!-- Button trigger modal -->
    <button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">
      Connections
    </button>

    <!-- Modal -->
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title" id="myModalLabel">History</h4>
          </div>
          <div class="modal-body">
            <ul>
              {% for connected_user in recent_connect_user %}
              <li> <a href="{{url_for('main.profile', username=connected_user.username)}}">{{connected_user.firstname}} {{connected_user.lastname}}</a></li>
              {% endfor %}
            </ul>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          </div>
        </div>
      </div>
    </div>
	</div>

	<div class="col-md-4">
	    {{ wtf.quick_form(form) }}
	</div>

</div>
{% endblock %}

app/templates/main/user_profile.html
{% extends "base.html" %}
{% block title %}{{ user.username }}{% endblock %}
{% block page_content %}
<div class="row">
	<div class="col-md-3">
	</div>
	<div class="col-md-6">
	<img class="center-block" src="{{ qrcode(request.url_root + url_for('main.profile', username=user.username)[1:]) }}">
	<h1>{{ user.firstname }} {{ user.lastname }}</h1>
	<ul>
		<li class="email">
			<i class="fa fa-envelope-o fa-1g"></i>
			<a href="mailto:{{user.email}}">{{user.email}}</a>
		</li>
		{% if user.twitter %}
		<li class="twitter">
			<i class="fa fa-twitter fa-1g"></i>
			<a target="_blank" href="https://twitter.com/{{user.twitter}}" title="{{user.username}}'s twitter">{{user.twitter}}</a>
		</li>
		{% endif %}
		{% if user.spotify %}
		<li class="spotify">
			<i class="fa fa-spotify fa-1g"></i>
			<a target="_blank" href="https://open.spotify.com/user/{{user.spotify}}" title="{{user.username}}'s spotify">{{user.spotify}}</a>
		</li>
		{% endif %}
		{% if user.phone %}
		<li class="phone">
			<i class="fa fa-phone fa-1g"></i>
			<a href="tel:{{user.phone}}" title="Call {{user.username}}">{{user.phone}}</a>
		</li>
		{% endif %}

		{% if user.skype %}
		<li class="skype">
			<i class="fa fa-skype fa-1g"></i>
			<a target="_blank" href="skype:{{user.skype}}?call" title="Skype {{user.username}}">{{user.skype}}</a>
		</li>
		{% endif %}

		{% if user.twitch %}
		<li class="twitch">
			<i class="fa fa-twitch fa-1g"></i>
			<a target="_blank" href="http://www.twitch.tv/{{user.twitch}}/profile" title="Twitch">{{user.twitch}}</a>
		</li>
		{% endif %}
		{% if user.instagram %}
		<li class="instagram">
			<i class="fa fa-instagram fa-1g"></i>
			<a target="_blank" href="https://instagram.com/{{user.instagram}}" title="Instagram">{{user.instagram}}</a>
		</li>
		{% endif %}
		{% if user.reddit %}
		<li class="reddit">
			<i class="fa fa-reddit fa-1g"></i>
			<a target="_blank" href="https://www.reddit.com/user/{{user.reddit}}" title="Reddit">{{user.reddit}}</a>
		</li>
		{% endif %}
		{% if user.github %}
		<li class="github">
			<i class="fa fa-github fa-1g"></i>
			<a target="_blank" href="https://github.com/{{user.github}}" title="Github">{{user.github}}</a>
		</li>
		{% endif %}
		{% if user.steam %}
		<li class="steam">
			<i class="fa fa-steam fa-1g"></i>
			<a target="_blank" href="http://steamcommunity.com/profiles/{{user.steam}}" title="Steam">{{user.steam}}</a>
		</li>
		{% endif %}
		{% if user.linkedin %}
		<li class="linkedin">
			<i class="fa fa-linkedin fa-1g"></i>
			<a target="_blank" href="https://www.linkedin.com/profile/view?id={{user.linkedin}}" title="Linkedin">{{user.linkedin}}</a>
		</li>
		{% endif %}
		{% if user.pinterest %}
		<li class="pinterest">
			<i class="fa fa-pinterest fa-1g"></i>
			<a target="_blank" href="https://www.pinterest.com/{{user.pinterest}}" title="Pinterest">{{user.pinterest}}</a>
		</li>
		{% endif %}
		{% if user.googleplus %}
		<li class="googleplus">
			<i class="fa fa-google-plus fa-1g"></i>
			<a target="_blank" href="https://plus.google.com/{{user.googleplus}}/about" title="Google+">{{user.googleplus}}</a>
		</li>
		{% endif %}
		{% if user.alibaba %}
		<li class="alibaba">
			Alibaba:
			<a target="_blank" href="http://{{user.alibaba}}.en.alibaba.com/" title="Aliaba">{{user.alibaba}}'s profile</a>
		{% endif %}
	</ul>
	{% if current_user != user %}
		{% if current_user.is_following(user) %}
		<button type="button" class="btn btn-primary btn-lg" onclick="location.href='{{url_for('main.disconnect_user', username=user.username)}}'">Unfollow</button>
		{% else %}
			<button type="button" class="btn btn-primary btn-lg" onclick="location.href='{{url_for('main.connect_user', username=user.username)}}'">Follow</button>
		{% endif %}
	{% endif %}
</div>
	<div class="col-md-3">
	</div>
</div>
{% endblock %}